name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    steps:
    # 1. Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3
    # Dependency installation and caching
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-node-
    # Type Check
    # - name: Type Check
    #   run: npm run type-check
    # 2. Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    # 3. Install dependencies
    - name: Install dependencies
      run: npm ci
    # 4. Run linting
    - name: Run ESLint
      run: npm run lint
    # 5. Build the project
    - name: Build project
      run: npm run build
    # 6. Start the app and run Cypress tests
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
    #   with:
    #     start: npm start
    #     wait-on: http://localhost:3000
    #     wait-on-timeout: 60
    # 7. Upload Cypress screenshots (if any)
    - name: Upload Cypress screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    # 8. Upload Cypress videos (if any)
    - name: Upload Cypress videos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: cypress/videos
